# Generated by Django 3.1 on 2020-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_create_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='email',
            field=models.CharField(max_length=120),
        ),
    ]
