# Generated by Django 3.1 on 2020-10-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201010_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='dob',
            field=models.CharField(max_length=120),
        ),
    ]
