# Generated by Django 3.1 on 2020-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20201013_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='user',
            field=models.CharField(default='user', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='create',
            name='dob',
            field=models.CharField(max_length=120),
        ),
    ]
